import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  wrapper: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg)",
    padding: 16,
  },
  card: {
    width: "100%",
    maxWidth: 380,
    background: "var(--surface)",
    padding: 32,
    borderRadius: 8,
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  title: {
    margin: "0 0 24px",
    fontSize: 24,
    fontWeight: 600,
    textAlign: "center",
  },
  field: { marginBottom: 16 },
  label: {
    display: "block",
    marginBottom: 6,
    fontSize: 14,
    color: "var(--text)",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: 14,
    border: "1px solid var(--border)",
    borderRadius: 6,
    outline: "none",
    boxSizing: "border-box",
  },
  button: {
    width: "100%",
    padding: "10px 12px",
    fontSize: 15,
    fontWeight: 500,
    color: "var(--on-accent)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    marginTop: 8,
  },
  buttonDisabled: { background: "var(--accent-disabled)", cursor: "not-allowed" },
  error: {
    padding: "8px 12px",
    marginBottom: 12,
    background: "var(--danger-bg)",
    color: "var(--danger)",
    border: "1px solid var(--danger-border)",
    borderRadius: 6,
    fontSize: 13,
  },
  footer: {
    marginTop: 20,
    fontSize: 14,
    textAlign: "center",
    color: "var(--text-muted)",
  },
  link: { color: "var(--accent)", textDecoration: "none" },
};
