import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  wrapper: { padding: "clamp(16px, 4vw, 32px)", maxWidth: 1000, margin: "0 auto" },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    flexWrap: "wrap",
    marginBottom: 32,
    padding: "clamp(16px, 4vw, 24px)",
    background: "var(--surface)",
    borderRadius: 8,
    border: "1px solid var(--border)",
  },
  topBar: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: 16,
  },
  logoutBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
    flexShrink: 0,
    padding: "8px 14px",
    background: "var(--surface)",
    color: "var(--danger)",
    border: "1px solid var(--danger-border)",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    background: "var(--accent-soft)",
    color: "var(--accent-text)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    fontWeight: 600,
    flexShrink: 0,
  },
  title: { margin: "0 0 4px", fontSize: 22, fontWeight: 600 },

  section: { marginBottom: 32 },
  sectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  sectionTitle: { margin: "0 0 16px", fontSize: 18, fontWeight: 600 },

  // Таблицы
  tableScroll: {
    overflowX: "auto",
    background: "var(--surface)",
    borderRadius: 8,
    border: "1px solid var(--border)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    background: "var(--surface-2)",
    borderBottom: "1px solid var(--border)",
    color: "var(--text)",
    fontWeight: 600,
    fontSize: 13,
    whiteSpace: "nowrap",
  },
  thCenter: { textAlign: "center" },
  td: {
    padding: "10px 14px",
    borderBottom: "1px solid var(--surface-2)",
    color: "var(--text)",
    verticalAlign: "top",
  },
  tdCenter: { textAlign: "center" },
  nowrap: { whiteSpace: "nowrap" },
  note: { color: "var(--text)", lineHeight: 1.4 },

  // Бейджи
  gradeBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 28,
    height: 28,
    padding: "0 8px",
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 600,
  },
  gradeStatus: { background: "var(--warn-bg)", color: "var(--warn)" },
  avg: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 600,
  },

  // Кнопка экспорта
  exportBtn: {
    padding: "8px 16px",
    background: "var(--ok)",
    color: "var(--on-accent)",
    border: "none",
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  exportBtnDisabled: {
    background: "var(--border)",
    color: "var(--text-muted)",
    cursor: "not-allowed",
  },

  // Селект предмета
  select: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--surface)",
    fontSize: 14,
    color: "var(--text)",
    cursor: "pointer",
    minWidth: 200,
    maxWidth: "100%",
    boxSizing: "border-box",
  },

  // Домашнее задание
  hwList: { display: "flex", flexDirection: "column", gap: 12 },
  hwCard: {
    padding: 16,
    background: "var(--surface)",
    borderRadius: 8,
    border: "1px solid var(--border)",
  },
  hwMeta: {
    display: "flex",
    gap: 16,
    marginBottom: 8,
    fontSize: 13,
    flexWrap: "wrap",
  },
  hwGiven: { color: "var(--text-muted)" },
  hwDue: { color: "var(--warn)", fontWeight: 600 },
  hwTask: { margin: 0, color: "var(--text)", lineHeight: 1.5, whiteSpace: "pre-wrap" },

  muted: { color: "var(--text-muted)", fontSize: 13, margin: 0 },
  loading: { padding: 40, textAlign: "center", color: "var(--text-muted)" },
  error: {
    padding: "10px 14px",
    background: "var(--danger-bg)",
    color: "var(--danger)",
    border: "1px solid var(--danger-border)",
    borderRadius: 6,
    fontSize: 13,
  },
  empty: {
    padding: 40,
    textAlign: "center",
    color: "var(--text-muted)",
    background: "var(--surface)",
    borderRadius: 8,
    border: "1px solid var(--border)",
  },
};

