
export const styles: Record<string, React.CSSProperties> = {
  wrapper: { padding: 32, maxWidth: 1200, margin: "0 auto" },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 24,
    gap: 16,
  },
  back: { color: "#2563eb", textDecoration: "none", fontSize: 14 },
  pageTitle: { margin: "8px 0 0", fontSize: 22, fontWeight: 600 },
  helper: {
    padding: 12,
    marginBottom: 16,
    background: "#fff7ed",
    color: "#9a3412",
    border: "1px solid #fed7aa",
    borderRadius: 6,
    fontSize: 13,
  },
  link: { color: "#2563eb", textDecoration: "none" },

  // Toolbar (фильтры)
  toolbar: {
    display: "flex",
    gap: 16,
    alignItems: "flex-end",
    flexWrap: "wrap",
    marginBottom: 16,
    padding: 16,
    background: "#fff",
    borderRadius: 8,
    border: "1px solid #e5e5ea",
  },

  // Table
  tableWrap: {
    background: "#fff",
    border: "1px solid #e5e5ea",
    borderRadius: 8,
    overflow: "hidden",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
  th: {
    padding: "10px 14px",
    textAlign: "left",
    background: "#fafafa",
    borderBottom: "1px solid #e5e5ea",
    fontWeight: 600,
    color: "#333",
    fontSize: 13,
  },
  thActions: { width: 200, textAlign: "right" },
  td: { padding: "10px 14px", borderBottom: "1px solid #f0f0f3" },
  tdActions: { textAlign: "right", whiteSpace: "nowrap" },

  // Buttons
  btnPrimary: {
    padding: "8px 14px",
    fontSize: 14,
    fontWeight: 500,
    color: "#fff",
    background: "#2563eb",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "6px 12px",
    fontSize: 13,
    color: "#333",
    background: "#fff",
    border: "1px solid #d0d0d5",
    borderRadius: 6,
    cursor: "pointer",
    marginRight: 6,
  },
  btnDanger: {
    padding: "6px 12px",
    fontSize: 13,
    color: "#b00020",
    background: "#fff",
    border: "1px solid #fbb",
    borderRadius: 6,
    cursor: "pointer",
  },

  // Empty / loading / error
  loading: { padding: 40, textAlign: "center", color: "#666" },
  empty: {
    padding: 40,
    textAlign: "center",
    color: "#666",
    background: "#fff",
    borderRadius: 8,
    border: "1px solid #e5e5ea",
  },
  error: {
    padding: "10px 14px",
    marginBottom: 16,
    background: "#fee",
    color: "#b00020",
    border: "1px solid #fbb",
    borderRadius: 6,
    fontSize: 13,
  },

  // Modal
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 100,
  },
  modal: {
    width: "100%",
    maxWidth: 440,
    background: "#fff",
    borderRadius: 8,
    boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
    overflow: "hidden",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    borderBottom: "1px solid #e5e5ea",
  },
  modalTitle: { margin: 0, fontSize: 17, fontWeight: 600 },
  closeBtn: {
    width: 28,
    height: 28,
    fontSize: 22,
    lineHeight: 1,
    color: "#666",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  modalBody: { padding: 20 },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 20,
  },

  // Fields
  field: { display: "block", marginBottom: 14 },
  fieldLabel: {
    display: "block",
    marginBottom: 6,
    fontSize: 13,
    color: "#333",
    fontWeight: 500,
  },
  input: {
    width: "100%",
    padding: "8px 10px",
    fontSize: 14,
    border: "1px solid #d0d0d5",
    borderRadius: 6,
    outline: "none",
    boxSizing: "border-box",
    background: "#fff",
  },
};
