import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  wrapper: { padding: 32, maxWidth: 1200, margin: "0 auto" },
  wrapperMobile: { padding: "20px 16px 40px" },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 24,
    gap: 16,
  },
  pageHeaderMobile: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
  },
  back: { color: "var(--accent)", textDecoration: "none", fontSize: 14 },
  pageTitle: { margin: "8px 0 0", fontSize: 22, fontWeight: 600, color: "var(--text)" },
  helper: {
    padding: 12,
    marginBottom: 16,
    background: "var(--accent-soft)",
    color: "var(--accent-text)",
    border: "1px solid var(--accent-border)",
    borderRadius: 8,
    fontSize: 13,
  },
  link: { color: "var(--accent)", textDecoration: "none" },

  toolbar: {
    display: "flex",
    gap: 16,
    alignItems: "flex-end",
    flexWrap: "wrap",
    marginBottom: 16,
    padding: 16,
    background: "var(--surface)",
    borderRadius: 12,
    border: "1px solid var(--border)",
  },

  tableWrap: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 14, color: "var(--text)" },
  th: {
    padding: "12px 14px",
    textAlign: "left",
    background: "var(--accent-soft)",
    borderBottom: "1px solid var(--border)",
    fontWeight: 600,
    color: "var(--accent-strong)",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    whiteSpace: "nowrap",
  },
  thActions: { width: 200, textAlign: "right" },
  td: { padding: "10px 14px", borderBottom: "1px solid var(--border-soft)", color: "var(--text)" },
  tdActions: { textAlign: "right", whiteSpace: "nowrap" },

  // Кнопки
  btnPrimary: {
    padding: "10px 18px",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--on-accent)",
    background: "var(--accent)",
    border: "none",
    borderRadius: 9,
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "7px 14px",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text)",
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    cursor: "pointer",
    marginRight: 6,
  },
  btnDanger: {
    padding: "7px 14px",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--danger)",
    background: "var(--surface)",
    border: "1px solid var(--danger-border)",
    borderRadius: 9,
    cursor: "pointer",
  },

  loading: { padding: 40, textAlign: "center", color: "var(--text-muted)" },
  empty: {
    padding: 40,
    textAlign: "center",
    color: "var(--text-muted)",
    background: "var(--surface)",
    borderRadius: 12,
    border: "1px solid var(--border)",
  },
  error: {
    padding: "10px 14px",
    marginBottom: 16,
    background: "var(--danger-bg)",
    color: "var(--danger)",
    border: "1px solid var(--danger-border)",
    borderRadius: 8,
    fontSize: 13,
  },

  // модалка
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 100,
  },
  modal: {
    width: "100%",
    maxWidth: 440,
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    background: "var(--surface)",
    borderRadius: 12,
    boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
    overflow: "hidden",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    borderBottom: "1px solid var(--border)",
  },
  modalTitle: { margin: 0, fontSize: 17, fontWeight: 600, color: "var(--text)" },
  closeBtn: {
    width: 28,
    height: 28,
    fontSize: 22,
    lineHeight: 1,
    color: "var(--text-muted)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  modalBody: { padding: 20, overflowY: "auto", flex: 1, minHeight: 0 },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 20,
  },

  field: { display: "block", marginBottom: 14 },
  fieldLabel: {
    display: "block",
    marginBottom: 6,
    fontSize: 13,
    color: "var(--text)",
    fontWeight: 500,
  },
  input: {
    width: "100%",
    padding: "8px 10px",
    fontSize: 14,
    border: "1px solid var(--border)",
    borderRadius: 8,
    outline: "none",
    boxSizing: "border-box",
    background: "var(--surface)",
    color: "var(--text)",
  },
};
